def K8S_REPO_BRANCH = 'main'
def K8S_DEPLOY_VALUE_FILE = "./charts/values.yaml"

pipeline {
  agent any

  stages {

    stage('Release Triggered Build') {
        steps {
            script {
                if (env.GITHUB_EVENT_NAME == 'release') {
                    if (env.GITHUB_EVENT_ACTION == 'published') {
                        env.RELEASE_TAG = env.GITHUB_REF_NAME
                        echo "Release published! Tag: ${env.RELEASE_TAG}. Triggering downstream job..."

                        build job: 'release-build', wait: false, parameters: [
                            string(name: 'RELEASE_TAG', value: env.RELEASE_TAG)
                        ]
                    } else {
                        echo "Not a publish action, skipping."
                    }
                } else {
                    echo "Not a release event."
                }
            }
        }
    }

    stage('Build Docker Image') {
      when {
        expression { return env.RELEASE_TAG?.trim() }
      }
      steps {
        sshagent(credentials: ['basedynamics']) {
          script {
            sh """
            git checkout ${K8S_REPO_BRANCH} && git pull origin ${K8S_REPO_BRANCH} --no-rebase
            sed -i "s/^\\(\\s*tag:\\s*\\).*/\\1${RELEASE_TAG}/" ${K8S_DEPLOY_VALUE_FILE}
            git add ${K8S_DEPLOY_VALUE_FILE}
            git commit -m "Latest Docker Image Tag Update: ${RELEASE_TAG}"
            git push origin ${K8S_REPO_BRANCH}
            """
          }
        }
      }
    }

  
  }
}

