def K8S_REPO_BRANCH = 'main'
def K8S_DEPLOY_VALUE_FILE = "./charts/values.yaml"

pipeline {
  agent any

  environment {
    RELEASE_TAG = ''
  }

  stages {

    stage('Check Release Event') {
        steps {
            script {
                def action = sh(
                    script: "echo '${env.GITHUB_PAYLOAD}' | jq -r .action",
                    returnStdout: true
                ).trim()

                if (action == 'published') {

                    env.RELEASE_TAG = sh(
                        script: "echo '${env.GITHUB_PAYLOAD}' | jq -r .release.tag_name",
                        returnStdout: true
                    ).trim()

                    echo "Release published! Tag: ${env.RELEASE_TAG}"

                } else {
                    echo "Not a release publish event"
                }
            }
        }
    }

    stage('Build Docker Image') {
      when {
        expression { return env.RELEASE_TAG?.trim() }
      }
      steps {
        sshagent(credentials: ['basedynamics']) {
          script {
            sh """
            git checkout ${K8S_REPO_BRANCH} && git pull origin ${K8S_REPO_BRANCH} --no-rebase
            sed -i "s/^\\(\\s*tag:\\s*\\).*/\\1${RELEASE_TAG}/" ${K8S_DEPLOY_VALUE_FILE}
            git add ${K8S_DEPLOY_VALUE_FILE}
            git commit -m "Latest Docker Image Tag Update: ${RELEASE_TAG}"
            git push origin ${K8S_REPO_BRANCH}
            """
          }
        }
      }
    }

  
  }
}

