apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-calculator
  namespace: java
spec:
  replicas: 1

  selector:
    matchLabels:
      app: java-calculator

  template:
    metadata:
      labels:
        app: java-calculator

    spec:
      containers:
        - name: java-calculator
          image: alpha260/java-calculator:v1.1
          imagePullPolicy: Always