apiVersion: v1
kind: Service
metadata:
  name: java-calculator
  namespace: java
spec:
  selector:
    app: java-calculator

  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

  type: ClusterIP