def K8S_REPO_BRANCH = 'main'
def K8S_DEPLOY_VALUE_FILE = "./charts/values.yaml"
def ENV = 'main'
def NOW = new Date().format("dd-MM-yyyy-HH-mm-ss", TimeZone.getTimeZone('UTC'))

pipeline {
  agent any

  stages {

    stage('Build Docker Image') {
      when {
        expression { return env.RELEASE_TAG?.trim() }
      }
      steps {
        sshagent(credentials: ['basedynamics']) {
          script {
            def tag = "${ENV}-${NOW}"
            sh """

            git checkout ${K8S_REPO_BRANCH} && git pull origin ${K8S_REPO_BRANCH} --no-rebase
            sed -i "s/^\\(\\s*tag:\\s*\\).*/\\1${tag}/" ${K8S_DEPLOY_VALUE_FILE}
            git add ${K8S_DEPLOY_VALUE_FILE}
            git commit -m "Latest Docker Image Tag Update: ${tag}"
            git push origin ${K8S_REPO_BRANCH}
            """
          }
        }
      }
    }

    stage('Tag Git Repo') {
      steps {
        sshagent(credentials: ['basedynamics']) {
          script {
            def tag = "${ENV}-${NOW}"
            sh """
              
              # Check if tag already exists
              if git rev-parse "${tag}" >/dev/null 2>&1; then
                echo "Tag ${tag} already exists, skipping"
              else
                git tag ${tag}
                git push origin ${tag}
              fi
            """
          }
        }
      }
    }
  
  }
}

